### ISSUE TITLE
on Mac, on 'pip3 install -r requirements.txt'

### ISSUE THREAD

**Issue by ctzurcanu** [touretzkyds/cozmo-tools#25]
the error is:

Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-install-6yqcfqj4/PyOpenGL-accelerate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-record-j6rpnctw/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-install-6yqcfqj4/PyOpenGL-accelerate/

**Comment by touretzkyds** [comment]
Python support on the Mac sucks.  It's possible that PyOpenGL-accelerate isn't available for Python 3.7 yet. Try installing Python 3.6 instead.

**Comment by ctzurcanu** [comment]
created another env with anaconda.

Now the error is:

Command "/Users/user/anaconda3/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-install-lw0ck3be/PyOpenGL-accelerate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-record-hs6grphj/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-install-lw0ck3be/PyOpenGL-accelerate/

I read it as being the same error. :(

**Comment by ctzurcanu** [comment]
the part of interest is:

Building wheels for collected packages: PyOpenGL-accelerate
  Running setup.py bdist_wheel for PyOpenGL-accelerate ... error
  Complete output from command /Users/user/anaconda3/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-install-g0wgvss5/PyOpenGL-accelerate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-wheel-ftwopgvc --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.6
  creating build/lib.macosx-10.9-x86_64-3.6/OpenGL_accelerate
  copying ./__init__.py -> build/lib.macosx-10.9-x86_64-3.6/OpenGL_accelerate
  copying ./setup.py -> build/lib.macosx-10.9-x86_64-3.6/OpenGL_accelerate
  running build_ext
  building 'OpenGL_accelerate.wrapper' extension
  creating build/temp.macosx-10.9-x86_64-3.6
  creating build/temp.macosx-10.9-x86_64-3.6/src
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/user/anaconda3/envs/py36/include -mmacosx-version-min=10.9 -m64 -fPIC -I/Users/user/anaconda3/envs/py36/include -mmacosx-version-min=10.9 -m64 -fPIC -I/private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-install-g0wgvss5/PyOpenGL-accelerate/.. -I/private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-install-g0wgvss5/PyOpenGL-accelerate/src -I/private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-install-g0wgvss5/PyOpenGL-accelerate -I/Users/user/anaconda3/envs/py36/include/python3.6m -c src/wrapper.c -o build/temp.macosx-10.9-x86_64-3.6/src/wrapper.o
  In file included from src/wrapper.c:16:
  /Users/user/anaconda3/envs/py36/include/python3.6m/Python.h:25:10: fatal error: 'stdio.h' file not found
  #include <stdio.h>
           ^~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for PyOpenGL-accelerate
  Running setup.py clean for PyOpenGL-accelerate
Failed to build PyOpenGL-accelerate
Installing collected packages: PyOpenGL-accelerate, pyreadline
  Running setup.py install for PyOpenGL-accelerate ... error
    Complete output from command /Users/user/anaconda3/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-install-g0wgvss5/PyOpenGL-accelerate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-record-pnq7501k/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.6
    creating build/lib.macosx-10.9-x86_64-3.6/OpenGL_accelerate
    copying ./__init__.py -> build/lib.macosx-10.9-x86_64-3.6/OpenGL_accelerate
    copying ./setup.py -> build/lib.macosx-10.9-x86_64-3.6/OpenGL_accelerate
    running build_ext
    building 'OpenGL_accelerate.wrapper' extension
    creating build/temp.macosx-10.9-x86_64-3.6
    creating build/temp.macosx-10.9-x86_64-3.6/src
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/user/anaconda3/envs/py36/include -mmacosx-version-min=10.9 -m64 -fPIC -I/Users/user/anaconda3/envs/py36/include -mmacosx-version-min=10.9 -m64 -fPIC -I/private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-install-g0wgvss5/PyOpenGL-accelerate/.. -I/private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-install-g0wgvss5/PyOpenGL-accelerate/src -I/private/var/folders/s_/_xpjyq_j0l7bs262tw_8flcw0000gn/T/pip-install-g0wgvss5/PyOpenGL-accelerate -I/Users/user/anaconda3/envs/py36/include/python3.6m -c src/wrapper.c -o build/temp.macosx-10.9-x86_64-3.6/src/wrapper.o
    In file included from src/wrapper.c:16:
    /Users/user/anaconda3/envs/py36/include/python3.6m/Python.h:25:10: fatal error: 'stdio.h' file not found
    #include <stdio.h>
             ^~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1

**Comment by touretzkyds** [comment]
As I said before, Python support on the Mac sucks. In particular, the people who maintain Python packages for the Mac seem to be doing a poor job of it. If PyOpenGL-accelerate isn't available for Python 3.7, complain to the package maintainers, or switch to Python 3.6.

**Comment by ctzurcanu** [comment]
Sorry,

I thought it was clear that I had already made a new env in anaconda with python 3.6. Then I tried again and got the error above.
I will try on a Linux, but this month I am not home and I only have access to this laptop that does not have enough room for a virtual OS or a new HD partition.

**Comment by touretzkyds** [comment]
Ah, I missed that the anaconda try was with 3.6, not 3.7.

The code might work even without PyOpenGL-accelerate, as long as you have PyOpenGL itself. You could try that.

The other option is to try Python 3.5. I'm pretty sure it works there.
