### ISSUE TITLE
Module Import Errors

### ISSUE THREAD

**Issue by VictorTagayun** [touretzkyds/cozmo-tools#30]
Newbie here.
I tried to run cam_viewer.py

1st I got this error

`ModuleNotFoundError: No module named 'scipy'`

fixed with by install Jupyter, etc...

2nd I cannot find the solution

`ImportError: cannot import name 'opengl'`

Should it be included in requirements.txt?

**Comment by touretzkyds** [comment]
See http://Cozmopedia.org for instructions for installing OpenGL for Python.

**Comment by VictorTagayun** [comment]
I forgot how I solved scipy, do you have instructions on how to?
This is just for documentation purposes for others too.

**Comment by touretzkyds** [comment]
Also, the "opengl" module is part of cozmo_fsm; it is not a Python package.

**Comment by VictorTagayun** [comment]
Hello I followed like this:

```
acer@acer-Aspire-6935:~$ sudo apt-get install freeglut3
Reading package lists... Done
Building dependency tree
Reading state information... Done
freeglut3 is already the newest version (2.8.1-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
acer@acer-Aspire-6935:~$ pip3 install PyOpenGL PyOpenGL_accelerate
Collecting PyOpenGL
Collecting PyOpenGL_accelerate
Installing collected packages: PyOpenGL, PyOpenGL-accelerate
Successfully installed PyOpenGL-3.1.0 PyOpenGL-accelerate-3.1.0
acer@acer-Aspire-6935:~$
```

And I still get this error

```
acer@acer-Aspire-6935:~/cozmo-tools/cozmo_fsm$ python3 cam_viewer.py
Traceback (most recent call last):
  File "cam_viewer.py", line 36, in <module>
    from . import opengl
ImportError: cannot import name 'opengl'
acer@acer-Aspire-6935:~/cozmo-tools/cozmo_fsm$
```

**Comment by touretzkyds** [comment]
cam_viewer is not a standalone program that can be run from the command line. It is a work in progress that is intended to be integrated into program.py and simple_cli. But we're still working on it. So don't worry about it for now. We have a different camera viewer that is already built in to program.py and works fine, except on Macs, because tkinter is messed up on Macs.

**Comment by VictorTagayun** [comment]
Sorry to disturb again, when I run program.py I have this problem:

```
acer@acer-Aspire-6935:/mnt/2TB/Hobby/Cozmo/cozmo-tools/cozmo_fsm$ python3 program.py
Traceback (most recent call last):
  File "program.py", line 13, in <module>
    from .evbase import EventRouter
ModuleNotFoundError: No module named '__main__.evbase'; '__main__' is not a package
```

**Comment by touretzkyds** [comment]
None of the code in the cozmo_fsm directory is meant to be run directly, so stop doing that.

The only thing you're supposed to run is simple_cli. From within there you can execute a program using the runfsm function.

Try the following:
1. Put the cozmo-tools directory on your search path (PATH variable).
2. cd to the cozmo-tools/cozmo_fsm/examples directory
3. Run simple_cli
4. Type this in simple_cli:    runfsm('Greet')
