### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TuanMr** [touretzkyds/cozmo-tools#58]
i don't how to add:
4. To get simple_cli and genfsm to work, add the following to your $Profile:
   function simple_cli() { py -i C:\Users\<username>\...\cozmo-tools\simple_cli }
   function genfsm($file) { py C:\Users\<username>\...\cozmo-tools\genfsm $file }

**Comment by touretzkyds** [comment]
This only applies to Windows systems. Open powershell and do "echo $Profile" to find the path to your profile file. Then edit that file (or create it if it doesn't already exist) using whatever text editor you like (e.g., Notepad) and add the two lines above.
